-- ─────────────────────────────────────────────────────────────────────────────
-- Grog Partner Dashboard — Database Schema
-- Run in Supabase SQL Editor in order: 001 → 002
-- ─────────────────────────────────────────────────────────────────────────────

-- ─── Dashboard Users ─────────────────────────────────────────────────────────

create table dashboard_users (
  id          uuid references auth.users primary key,
  email       text unique not null,
  name        text,
  role        text default 'member' check (role in ('admin', 'member')),
  created_at  timestamptz default now(),
  created_by  uuid references dashboard_users(id),
  last_login  timestamptz
);

-- ─── Form Config ─────────────────────────────────────────────────────────────

create table form_config (
  id          bigint generated by default as identity primary key,
  category    text not null check (category in ('personal', 'bar', 'club', 'artist', 'creator')),
  step        int  not null,
  step_title  text not null,
  fields      jsonb not null,
  updated_at  timestamptz default now(),
  updated_by  uuid references dashboard_users(id),
  unique(category, step)
);

-- ─── Bot Signals ─────────────────────────────────────────────────────────────

create table bot_signals (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz default now(),
  signal       text not null,
  processed    boolean default false,
  processed_at timestamptz
);

-- ─── Settings ────────────────────────────────────────────────────────────────

create table settings (
  key         text primary key,
  value       text not null,
  updated_at  timestamptz default now(),
  updated_by  uuid references dashboard_users(id)
);

-- ─── Audit Log ───────────────────────────────────────────────────────────────

create table audit_log (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz default now(),
  user_id     uuid references dashboard_users(id),
  user_email  text,
  action      text,
  target_type text,
  target_id   text,
  meta        jsonb
);

-- ─── Partner Applications (core table used by bot + dashboard) ───────────────

create table if not exists partner_applications (
  id               bigint generated by default as identity primary key,
  created_at       timestamptz default now(),
  discord_id       text not null,
  discord_username text,
  full_name        text,
  email            text,
  phone            text,
  dob              text,
  address          text,
  city             text,
  state            text,
  zip              text,
  country          text,
  category         text,
  answers          jsonb,
  status           text default 'pending',
  reviewed_by      text,
  review_note      text,
  dm_sent          boolean default true
);

-- ─── Seed Default Settings ───────────────────────────────────────────────────

insert into settings (key, value) values
  ('role_id_creator', ''),
  ('role_id_artist', ''),
  ('role_id_club', ''),
  ('role_id_bar', ''),
  ('admin_channel_id', ''),
  ('dm_approve_template', E'🍋 **You''re in!**\n\nWelcome to the Grog Partner Program! Your private channels are now unlocked.\n\nLet''s cook something fun together 🍹'),
  ('dm_reject_template', E'Hey! Thanks for applying to the Grog Partner Program.\n\nUnfortunately we''re not moving forward right now — but keep your eyes open, things change fast. Keep drinking Grog 🍊'),
  ('bot_heartbeat', ''),
  ('forms_last_loaded', '')
on conflict (key) do nothing;

-- ─── Helper Function ─────────────────────────────────────────────────────────

create or replace function is_dashboard_admin()
returns boolean as $$
  select exists (
    select 1 from dashboard_users
    where id = auth.uid() and role = 'admin'
  );
$$ language sql security definer;
