-- ─────────────────────────────────────────────────────────────────────────────
-- Grog Discord — Store Requests
-- ─────────────────────────────────────────────────────────────────────────────

create table store_requests (
  id              bigint generated by default as identity primary key,
  discord_id      text not null,
  discord_username text not null,
  store_name      text not null,
  store_address   text not null,
  visit_frequency text not null,
  notes           text,
  created_at      timestamptz default now()
);

create index store_requests_discord_id_idx on store_requests(discord_id);
create index store_requests_created_at_idx on store_requests(created_at desc);
